### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by suic1de666** [Leeon123/CC-attack#10]
how fix?
Traceback (most recent call last):
File "cc.py", line 361, in <module>
main()
File "cc.py", line 302, in main
ip = str(input("> Host/Ip:"))
File "<string>", line 1
79.133.43.229
SyntaxError: invalid syntax

**Comment by suic1de666** [comment]
on another server it works fine and in termux

**Comment by suic1de666** [comment]
but on the main machine does not work

**Comment by Leeon123** [comment]
Please use python3, and read README.md
