### ISSUE TITLE
(low priority) ssl method deprecated

### ISSUE THREAD

**Issue by Tsunami2360** [Leeon123/CC-attack#105]
I get these errors: 
`C:\cc-attack\cc.py:253: DeprecationWarning: ssl.SSLContext() without protocol argument is deprecated.
  ctx = ssl.SSLContext()
C:\cc-attack\cc.py:253: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  ctx = ssl.SSLContext()`
when I run:
`python3 ./cc.py -url https://url -down -f proxy.txt -v 5 -s 180 -b 1`

**Comment by swordapi** [comment]
Yeah me too but not always im not sure if its the websites fault

**Comment by Tsunami2360** [comment]
No, i'm quite sure it's not a bug provided by a website.
This warning shows up only when you're trying to attack https (443), but not for http, as it's related to SSL/TLS (ssl.SSLContext(), ssl.PROTOCOL_TLS).
One of the used libraries' methods was deprecated as we can see from the error.
I recommend that Leeon123 just has to update this project to use the newer version of the library...

**Comment by Leeon123** [comment]
Not a big deal. It is fixed in latest pre-release.
