### ISSUE TITLE
cant not use multiprocess

### ISSUE THREAD

**Issue by anzuukino** [Leeon123/CC-attack#107]
![image](https://user-images.githubusercontent.com/86243871/208440211-0136dc93-53b7-4d69-9bed-e7817913b94a.png)

I cant not use this, Am I wrong ?

**Comment by anzuukino** [comment]
Am I do something wrong ?

**Comment by Leeon123** [comment]
It's just because you are not using linux. 
And I added multiprocessing support in preview version, no need to use bash script anymore.

Go check it out.
