### ISSUE TITLE
Cara memperbaiko tolong

### ISSUE THREAD

**Issue by TheGetsuzoZhiro** [Leeon123/CC-attack#110]
/home/kali/Desktop/CC-attack/cc.py:253: DeprecationWarning: ssl.SSLContext() without protocol argument is deprecated.
  ctx = ssl.SSLContext()
/home/kali/Desktop/CC-attack/cc.py:253: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  ctx = ssl.SSLContext()

**Comment by Leeon123** [comment]
Just a warning, not a big deal. I guess
