### ISSUE TITLE
DeprecationWarning: ssl.SSLContext() without protocol argument is deprecated.  

### ISSUE THREAD

**Issue by MiChaelinzo** [Leeon123/CC-attack#117]
```
/home/BOTNET/CC-attack/cc.py:253: DeprecationWarning: ssl.SSLContext() without protocol argument is deprecated.
  ctx = ssl.SSLContext()
/home/CC-attack/cc.py:253: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  ctx = `ssl.SSLContext()
```

The error message provided is related to the use of ssl.SSLContext() without a protocol argument, which is deprecated in Python 3.10 ](https://docs.python.org/3/library/ssl.html)[1](https://docs.python.org/3/library/ssl.html). [Instead, you should use ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT) or ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER) as per your requirement ](https://stackoverflow.com/questions/72306332/python3-deprecationwarning-ssl-protocol-tlsv1-2-is-deprecated-sslcontext-ssl)[2](https://stackoverflow.com/questions/72306332/python3-deprecationwarning-ssl-protocol-tlsv1-2-is-deprecated-sslcontext-ssl). [Similarly, ssl.PROTOCOL_TLS is also deprecated in Python 3.10 ](https://docs.python.org/3/library/ssl.html)[1](https://docs.python.org/3/library/ssl.html). You can use ssl.PROTOCOL_TLS_CLIENT or ssl.PROTOCOL_TLS_SERVER instead

**Comment by operationairstrike** [comment]
This is caused by the website, it doesn't have valid ssl

**Comment by C1audiuss** [comment]
I ve same error, i thing it s from server

**Comment by operationairstrike** [comment]
Yes server causes it

**Comment by MiChaelinzo** [comment]
> Yes server causes it

it is not the server but the code itself using a use of SSLContext in Python. [The error message indicates that the SSLContext() function is being used without a protocol argument, which is now deprecated ](https://stackoverflow.com/questions/72306332/python3-deprecationwarning-ssl-protocol-tlsv1-2-is-deprecated-sslcontext-ssl) (https://stackoverflow.com/questions/72306332/python3-deprecationwarning-ssl-protocol-tlsv1-2-is-deprecated-sslcontext-ssl) (https://github.com/eclipse/paho.mqtt.python/issues/653). [Instead, you should use either ssl.PROTOCOL_TLS_CLIENT or ssl.PROTOCOL_TLS_SERVER as per your requirement ](https://stackoverflow.com/questions/72306332/python3-deprecationwarning-ssl-protocol-tlsv1-2-is-deprecated-sslcontext-ssl) (https://stackoverflow.com/questions/72306332/python3-deprecationwarning-ssl-protocol-tlsv1-2-is-deprecated-sslcontext-ssl) (https://github.com/eclipse/paho.mqtt.python/issues/653). [The error message also indicates that ssl.PROTOCOL_TLS is deprecated ](https://github.com/eclipse/paho.mqtt.python/issues/653) (https://github.com/eclipse/paho.mqtt.python/issues/653). [You can find more information about this error and how to fix it on the Python documentation website](https://stackoverflow.com/questions/72306332/python3-deprecationwarning-ssl-protocol-tlsv1-2-is-deprecated-sslcontext-ssl)

**Comment by C1audiuss** [comment]
i found it, it s because sytax it s not correct you must try http:// and not https://

**Comment by MiChaelinzo** [comment]
> i found it, it s because sytax it s not correct you must try http:// and not https://

Thanks, yes I know about it, that's why I put a link it doesn't support https etc.
