### ISSUE TITLE
New versions of running threads get stuck

### ISSUE THREAD

**Issue by zhaogea** [Leeon123/CC-attack#12]
New versions of running threads get stuck

**Comment by zhaogea** [comment]
Where can I buy more soket4/5?

**Comment by zhaogea** [comment]
Can we set up an HTTP proxy?

**Comment by Leeon123** [comment]
Frist, the threads control has bug and i will fix it later.Then, u can buy socks4/5 on any website that u could found from google. At Last, if u want to use http proxy, go to find Gogozin's ProKnight. Anyway, i will never use http proxy.

**Comment by zhaogea** [comment]
How to  bypass cf
Can you give me a hint?

**Comment by Leeon123** [comment]
Google it by yourself, You will find it.

**Comment by zhaogea** [comment]
That's why our script is useless, isn't it?

**Comment by zhaogea** [comment]
Thank you for sharing. It's not helpful to some people, though.
