### ISSUE TITLE
Can't Stop Running the Script!

### ISSUE THREAD

**Issue by GhostRecon03** [Leeon123/CC-attack#13]
I think that the python script having hard time sending a CTRL+C command to end the script

**Comment by Leeon123** [comment]
Can you explain what happened?

**Comment by GhostRecon03** [comment]
when I press ctrl+c it doesn't stop

**Comment by Leeon123** [comment]
Just closed the terminal now. I'll try to handle it in next version.

**Comment by Leeon123** [comment]
Now it is fixed.
