### ISSUE TITLE
> Socks5 Proxy file path(socks5.txt):socks.txt Traceback (most recent call last):   File "cc.py", line 558, in <module>     main()#Coded by Leeon123   File "cc.py", line 508, in main     proxies = open(out_file).readlines() FileNotFoundError: [Errno 2] No such file or directory: 'socks.txt'

### ISSUE THREAD

**Issue by darknodi** [Leeon123/CC-attack#15]
> Socks5 Proxy file path(socks5.txt):socks.txt
Traceback (most recent call last):
  File "cc.py", line 558, in <module>
    main()#Coded by Leeon123
  File "cc.py", line 508, in main
    proxies = open(out_file).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'socks.txt'

**Comment by Leeon123** [comment]
The socks5 proxies file are updated as "socks5.txt". And please check default setting of it :
 ```Socks5 Proxy file path(socks5.txt):socks.txt```
