### ISSUE TITLE
something is wrong with the proxy checker

### ISSUE THREAD

**Issue by Digiguy1** [Leeon123/CC-attack#16]
when i grab the list of proxy that the script download and go to proxyscrape.com and check it with their online proxy checker it get list of proxy that work but from the script it says Total Worked:0 . please help

**Comment by Leeon123** [comment]
Have you even try to use the list without check? If yes and it works well, then the proxy checker may have something wrong, but i never got this problem, and what domain or ip did you use in proxy checker?

**Comment by Digiguy1** [comment]
yes i do but it dont work

**Comment by Leeon123** [comment]
What did you do???

**Comment by Leeon123** [comment]
Try to use in-build proxy scraper and test with it's list.

**Comment by Digiguy1** [comment]
i got it to work for some reason if the site is behind a WAF the proxy checker will say Total Worked:0
but if the site is not behind a WAF it will work and find some proxy's that work will say something like Total Worked:270 out of like 10.200 proxy  its weird also realized i like the 2.1 version from the other versions it tried  but I like the tool its pretty impressive thanks for you contribution

**Comment by Leeon123** [comment]
Well, I will try to fix that situation(yeah i mean try to bypass waf), but anyway thank you for your approval.
