### ISSUE TITLE
Magnification?

### ISSUE THREAD

**Issue by DecodeMehh** [Leeon123/CC-attack#2]
Hello, can you explain what to put in magnification ?

**Comment by DecodeMehh** [comment]
Found i only put 100 but what is the point?

**Comment by Leeon123** [comment]
When you only flood a server with your own ip, the server may not accept all requests that you send to, so if you use socks4/5 server to send request , it will accept all request you send. The Magnification is about how many request you want to send with a connection. If you put 100 threads and 1 Magnification = 100x1,also 100 threads 100 magnification= 100x100.

**Comment by Leeon123** [comment]
Hope it can help you

**Comment by DecodeMehh** [comment]
Thanks :)

**Comment by osintyes** [comment]
![dsadsad](https://user-images.githubusercontent.com/52049434/61595250-11792500-abf5-11e9-8531-1693262cf96c.PNG)

Can you make an strongest script for Layer 7 Security Tool for HTTP and HTTPS request 

using python and python3, if, make as original like this. :)

**Comment by osintyes** [comment]
this script, functions for https protocol and path website, is very strongest ddosing tool for website. 
make an script, with these pmtrs.

**Comment by Leeon123** [comment]
nah, You should find me on discord but not here, and Ur script(LOL) just using parameter as config, u can edit this script too, learn more python skid.
