### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by 62019** [Leeon123/CC-attack#22]

**Comment by kotobukidevelopers** [comment]
this thing is working sir :) it depends on your target it's not a one shot one kill or maybe you are running on a system that limits your network packets to be sent :) 
don't use windows OS it will work but apparently your network will be filtered and limit
instead use a Linux system if you are using a linux alread try to run ulimit -n 999999 and then make sure you are on a private network not use a VPN/Proxy Server other problem is that your device/ip has been block by the site
