### ISSUE TITLE
www. in hosts Failed

### ISSUE THREAD

**Issue by kotobukidevelopers** [Leeon123/CC-attack#23]
if you add a www. in the host/ip/target

example: www.target.com
port 443 / ssl enabled is not working

showing thread error

**Comment by Leeon123** [comment]
Have any screenshot?

**Comment by kotobukidevelopers** [comment]
this is the result

[
![bug101](https://user-images.githubusercontent.com/58299166/72218330-ff10f000-3574-11ea-9ced-053c4658c935.png)
](url)

**Comment by Leeon123** [comment]
if not use www.? can u send more ss?

**Comment by kotobukidevelopers** [comment]
assuming that the website is configured to 2 states
www DNS and and without www.

when you visit the target without www. the host is not resolved while
with www it is resolved.

so the real url is like this www.iamtarget.com and not this iamtarget.com

choosing an attack of:
mode: cc
host: www.iamtarget.com
port: 80

this will send a CC flood

how ever when doing
mode: cc
hosts: www.iamtarget.com
port: 443

I got that error

**Comment by kotobukidevelopers** [comment]
the thing is that HTTPS is the right attack to create rather than HTTP only

**Comment by kotobukidevelopers** [comment]
when you visit http://www.iamtarget.com the site is down but if you visit https://www.iamtarget.com/ the site is up

**Comment by Leeon123** [comment]
so u can't attack https right?

**Comment by kotobukidevelopers** [comment]
yes indeed

**Comment by Leeon123** [comment]
smh, the script have already can't attack https for a long long time

**Comment by Leeon123** [comment]
I'll find a way later or u can improve it.

**Comment by kotobukidevelopers** [comment]
i'll send here a video

**Comment by amrelsadane123** [comment]
how i can attack port 443
