### ISSUE TITLE
www. in hosts Failed Video

### ISSUE THREAD

**Issue by kotobukidevelopers** [Leeon123/CC-attack#24]
https://mega.nz/#!oW5ARYLL!CvJliyVd_Up4OqeECzX6KLLQ0jqe2JerwdMLiANWFZI
hi this is the video from the last issue I have encounter hope this can help

**Comment by Leeon123** [comment]
Thanks god finally know what happened. The script can't use socks5 to visit that site with ssl so there are all removed when doing proxies checking.
