### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by dogwalkerg** [Leeon123/CC-attack#31]
能发个详细点的安装，和使用教程吗？

**Comment by HsGalaxy** [comment]
I think you just need install python3 and run "pip3 install requests pysocks
git clone https://github.com/Leeon123/CC-attack.git
cd CC-attack",and "python3 cc.py" when you want to use it.Then use it happly:)

**Comment by Leeon123** [comment]
安装python3+pip3之后打开cmd
pip3 install pysocks requests
python3 cc.py

**Comment by KLDGodY** [comment]
> 能发个详细点的安装，和使用教程吗？

建议买页端
