### ISSUE TITLE
Having a problem with getting a decent amount of working proxys

### ISSUE THREAD

**Issue by Kali95739** [Leeon123/CC-attack#38]
The first time I used this tool it worked great. Thanks very much for the hard work you put in. Its just since the second time I have been having a problem where it says checking proxy 0 proxys worked. Or maybe sometimes 1 proxy will work. And I try but then it freezes up most likely because I don't have enough proxys Is there a fix you have for that?

**Comment by Leeon123** [comment]
This is because those socks4/5 can't connect to your target server. Try to check proxy with a higher delay(timeout).

**Comment by wzyonggege** [comment]
That target mostly would ban your proxies while attacking.

**Comment by Kali95739** [comment]
Thanks for the answer I tried the delay option but it seems it stuck on one proxy is there any good alternative proxys that you would know of that would work?

**Comment by Leeon123** [comment]
Actually there are only the number stuck at the screen, other checkers are still running. Just wait until it is done. In my opinion, i always set the timeout at 10 second.
