### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jetski300** [Leeon123/CC-attack#39]
Hello dear! 
Can you pls upgrade socks5 list 
You get my star ☆ anyway! 
Very thanks!

**Comment by Leeon123** [comment]
Socks list are all scrape from api.

**Comment by jetski300** [comment]
Okay I think that sucks. I hope you can make the program the way it was! Or a new one😁. It was great !! Bye

**Comment by jetski300** [comment]
Sorry but I see you added new api. Does this work well again? How do I install that in termux
