### ISSUE TITLE
Problem?

### ISSUE THREAD

**Issue by lostonyx** [Leeon123/CC-attack#4]
Why is it that when I put "https" as "n" or port 80, most socks are marked offline?

**Comment by Leeon123** [comment]
Can you send me a screenshot to my email? Or may be your socks5 list cannot work in your country? For example, I have a USA socks5 server, but i can't use it in mainland China :)

**Comment by Leeon123** [comment]
Problem may solve, pls update your script and test it.

**Comment by lostonyx** [comment]
Same problem
With SSL: https://imgur.com/AbWgw8gl.png
Without SSL: https://imgur.com/ONUoGjrl.png

**Comment by Leeon123** [comment]
What is your port?
