### ISSUE TITLE
BAD URL

### ISSUE THREAD

**Issue by andress134** [Leeon123/CC-attack#42]
could you make the script send requests to any url?
if the url is in https: // target-url / hit or https: //target.url/index.php format. the script does not work
Also headers like that @Leeon123 
headers: {
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive',
        'Cache-Control': 'max-age=0',
        'Referer': url,
        'Upgrade-Insecure-Request': 1,
upgrade insiecure requests, etc

**Comment by Leeon123** [comment]
added url parser
