### ISSUE TITLE
Hi there Sir Leeon123. Can you read this ?

### ISSUE THREAD

**Issue by ictkmc01** [Leeon123/CC-attack#44]
I want you to bring back the port and ip option that use to attack
because the new CC-attack cant attack the normal website and i really love the older one with my friends too
It's easy to use and manual way 
Thank you.

**Comment by Leeon123** [comment]
Is Okay, but what is the meaning of can't attack the normal website?

**Comment by ictkmc01** [comment]
Like​
I​ cant​ attack 
www.csne.co.th
Or
siamrealms.net 
anymore
But.with the​ manual​ port
I​ can
The​ proxychecker said​ 0​ available
Everytime

**Comment by Leeon123** [comment]
Bro, please search about what is "url" pls.
