### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Cedric-Merlin** [Leeon123/CC-attack#5]
Hello, They are some connection error on the slow but with the CC  much more, if you I can help or I do something wrong could you tell me ?

**Comment by Leeon123** [comment]
Use a new socks5 list.
 The socks5 list update server of my script has stopped update for 3 days ago. I'm using my own list now. 
Go to google and find some new socks5 list can help you to solve this promblem.

**Comment by Cedric-Merlin** [comment]
ok thanks for help, what's difference between slow and CC now ?

**Comment by Cedric-Merlin** [comment]
> ok thanks for help I made it and it work just for slow, what's difference between slow and CC now ?

**Comment by Leeon123** [comment]
Slow mode is slow-attack like slowloris but there are using a lot of socks5 server, CC is normal http-flood,using a lot of socks5 to do a (d)dos
