### ISSUE TITLE
不懂问一下dalao

### ISSUE THREAD

**Issue by hydrog-enoxide** [Leeon123/CC-attack#56]
请问post数据是直接写在一个文本文件里面，然后使用时直接填写路径，是这样吗，不太懂操作，谢谢！

**Comment by Leeon123** [comment]
```
请问post数据是直接写在一个文本文件里面，然后使用时直接填写路径
```
沒錯

**Comment by hydrogenoxide111** [comment]
那请问添加自定义随机数据是在哪里呢？
我的意思是想这样：https://www.test.com/xxx.php?[随机]  这样可以吗？语法是什么？

**Comment by Leeon123** [comment]
Post 祇有自定義數據和隨機數據
像你說的那種是隨機url 目前我只添加了在Get 和head 的方法

**Comment by hydrogenoxide111** [comment]
那请问在url里面添加什么字符串呢？还是说是程序自动的？

**Comment by Leeon123** [comment]
自動的
