### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by flare-vida** [Leeon123/CC-attack#6]
Please leave your Telegram contact information.
I would like to discuss with you about the optimization of your program.
Also, I will reward you some money for upgrading your software. (100$-200$)

**Comment by flare-vida** [comment]
You are welcome to add me
[@seflow](https://t.me/seflow)

**Comment by flare-vida** [comment]
Hi,
To control several servers launch attack at the same time, it will be easier if you could make this program executable in one single command, for example, "python3 ccattack.py --target http://google.com --mode HTTP --threads 1000 --process 10"

Please add my telegram as soon as possible.

**Comment by Leeon123** [comment]
Emm... Actually, I have already written a command line version of it, and now i'm learning "Golang". I will as fast as possible to upgrade this project. Thanks for your idea and opinion.

**Comment by Leeon123** [comment]
Emm... Actually, I have already written a command line version of it, and now i'm learning "Golang". I will as fast as possible to upgrade this project. Thanks for your idea and opinion.

**Comment by Leeon123** [comment]
later will be update
