### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by b-7307** [Leeon123/CC-attack#62]
When I want to use my own proxy list each of which works I get:
> Checked 1513 proxies
> Checked all proxies, Total Worked:0

How is that possible🤷‍♂️
Thanks!

**Comment by hydrogenoxide-user** [comment]
你的目标太垃圾了。

**Comment by Leeon123** [comment]
Which type of proxy did your proxy list for?
Socks4 ? Socks5?

**Comment by b-7307** [comment]
I try it with both socks4 and 5

**Comment by Leeon123** [comment]
I mean what are the proxies type of your list? Where did you download it

**Comment by b-7307** [comment]
Oh sorry, here hookzof/socks5_list

**Comment by Leeon123** [comment]
what was the target u set?

**Comment by Leeon123** [comment]
I tested and it works well

**Comment by b-7307** [comment]
Hmm okay, thank you for your responses! Greetz
