### ISSUE TITLE
Where to download proxies???

### ISSUE THREAD

**Issue by Vadym-beep** [Leeon123/CC-attack#64]
When I tryed to use this tool at the end it says "There are no more proxies. Please download a new one."
So, **where** I need to get theese proxies??

**Comment by kenegdane** [comment]
> When I tryed to use this tool at the end it says "There are no more proxies. Please download a new one."
> So, **where** I need to get theese proxies??
There is a download proxies option in that script, choose "y" to download proxies.

**Comment by Vadym-beep** [comment]
Ok fine
