### ISSUE TITLE
Some Website Using Cloudflare...So Can You Use CloudScaper For Bypass THE IUAM

### ISSUE THREAD

**Issue by andhra21231** [Leeon123/CC-attack#70]
https://github.com/VeNoMouS/cloudscraper

You Can Use This To Bypass it

**Comment by andress134** [comment]
> 

cloudscraper is patched . !! Can;t be bypass new challenge

**Comment by andhra21231** [comment]
hm

**Comment by Leeon123** [comment]
I am lazy to do that, you can do it if you want. 
There are some project done it before. 
Such as [this](https://github.com/GogoZin/CF-Bypass-Dos/blob/master/cfbypass.py)
