### ISSUE TITLE
HTTP Proxy Support

### ISSUE THREAD

**Issue by ThomasCFelix** [Leeon123/CC-attack#76]
Hi, This script only supports socks 4/5 proxies. Please add support for **HTTP Proxy**.

**Comment by Leeon123** [comment]
Pending

**Comment by ThomasCFelix** [comment]
Add the proxies list I put here to get more proxies during attack.

**Socks5**
https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5
https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5
https://www.proxy-list.download/api/v1/get?type=socks5
https://www.proxyscan.io/download?type=socks5
https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt
https://www.my-proxy.com/free-socks-5-proxy.html
https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt
https://api.openproxylist.xyz/socks5.txt
https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt
https://www.freeproxychecker.com/result/socks4_proxies.txt
http://www.socks24.org/feeds/posts/default
https://www.freeproxychecker.com/result/socks5_proxies.txt
https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt


**Socks4**
https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks4
https://api.proxyscrape.com/?request=displayproxies&proxytype=socks4
https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt
https://www.proxy-list.download/api/v1/get?type=socks4
https://www.proxyscan.io/download?type=socks4
https://api.openproxylist.xyz/socks4.txt
https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt
https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt
https://www.my-proxy.com/free-socks-4-proxy.html
http://proxysearcher.sourceforge.net/Proxy%20List.php?type=socks
https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt
http://www.socks24.org/feeds/posts/default
https://www.freeproxychecker.com/result/socks4_proxies.txt


**HTTP**
https://api.proxyscrape.com/?request=displayproxies&proxytype=http
https://www.proxy-list.download/api/v1/get?type=http
https://www.proxyscan.io/download?type=http
http://spys.me/proxy.txt
https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt
https://api.openproxylist.xyz/http.txt
https://www.my-proxy.com/free-proxy-list.html
https://raw.githubusercontent.com/shiftytr/proxy-list/master/proxy.txt
https://www.my-proxy.com/free-anonymous-proxy.html
https://www.my-proxy.com/free-transparent-proxy.html
https://www.my-proxy.com/free-proxy-list-2.html
https://www.my-proxy.com/free-proxy-list-3.html
https://www.my-proxy.com/free-proxy-list-4.html
https://proxy50-50.blogspot.com
https://www.my-proxy.com/free-proxy-list-5.html
http://alexa.lr2b.com/proxylist.txt
http://rootjazz.com/proxies/proxies.txt
https://www.freeproxychecker.com/result/http_proxies.txt
https://www.my-proxy.com/free-socks-4-proxy.html
http://www.proxyserverlist24.top/feeds/posts/default
https://www.my-proxy.com/free-proxy-list-6.html
https://www.my-proxy.com/free-proxy-list-7.html
https://www.my-proxy.com/free-proxy-list-8.html
http://proxysearcher.sourceforge.net/Proxy%20List.php?type=http
https://www.my-proxy.com/free-proxy-list-9.html
https://www.my-proxy.com/free-proxy-list-10.html
https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt
https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt
https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt
https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt
https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt
https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt
https://raw.githubusercontent.com/opsxcq/proxy-list/master/list.txt
https://proxy-spider.com/api/proxies.example.txt
https://multiproxy.org/txt_all/proxy.txt

**Comment by Leeon123** [comment]
Supported, and some of the api I am lazy to handle it. Maybe I will add them someday.
