### ISSUE TITLE
POST request with parameters

### ISSUE THREAD

**Issue by HappyVibes** [Leeon123/CC-attack#8]
hey :)
im not familiar with python and i tried to send POST request with body parameters with something like that i found online -

<pre>
#from line 224
post_host = "POST " + url2 + "?=" + str(random.randint(0,20000)) + " HTTP/1.1\r\nHost: " + ip + "\r\n"
content = "Content-Type: application/x-www-form-urlencoded\r\n"
length = "Content-Length: 0 \r\nConnection: Keep-Alive\r\n"
refer = "Referer: http://"+ ip + url2 + "\r\n"
user_agent = "User-Agent: " + random.choice(useragents) + "\r\n"
accept = random.choice(acceptall)
<b>parameters "first=John&last=Doe\r\n"</b>#of course i also tried with one parameter
request = post_host + accept + refer + content + user_agent + length + <b>parameters</b> + "\r\n"
proxy = random.choice(proxies).strip().split(":")
</pre>

but it didnt work.. can someone please tell me how can i do it right?

**Comment by Leeon123** [comment]
Change the Content-Length to your parameters length :)

**Comment by HappyVibes** [comment]
thank you for your answer!
i tried what you said
the parameter is "name=john" so i change the Content-Length to 9, i also tried to remove the "\r\n" and also the "auto method ;D" -
```python
#from line 226
length = "Content-Length: "+str(len(parameters))+" \r\nConnection: Keep-Alive\r\n"
parameters = "name=john\r\n" #in this way i also tried without the "\r\n"
```
but none of these things work

**Comment by Leeon123** [comment]
cloud u send me ur version and i can fix it more clearly :) Please send to me email or add my discord: Leeon123#5277

**Comment by HappyVibes** [comment]
I sent it to you again (via your email - cuz the paste was expire🙂)

**Comment by Leeon123** [comment]
i will send the fixed version to you by email later.

**Comment by HappyVibes** [comment]
Thank you so much!

**Comment by HappyVibes** [comment]
Hello can you please delete this issue? Sorry
